local cfg = vim.g

cfg.go_template_autocreate = 0
cfg.o_version_warning = 1
cfg.go_code_completion_enabled = 1
cfg.go_code_completion_icase = 0
cfg.go_test_show_name = 1
cfg.go_play_open_browser = 0
cfg.go_auto_type_info = 1
cfg.go_info_mode = 'gopls'
cfg.go_auto_sameids = 1
cfg.go_doc_balloon = 1
cfg.go_doc_popup_window = 1
cfg.go_snippet_engine = 'ultisnips'
cfg.go_get_update = 1
cfg.go_textobj_enabled = 1
cfg.go_textobj_include_function_doc = 1
cfg.go_textobj_include_variable = 1
cfg.go_list_height = 0
cfg.go_asmfmt_autosave = 1
cfg.go_term_reuse = 1
cfg.go_term_enabled = 1
cfg.go_diagnostics_level = 2
cfg.go_decls_mode = 'fzf'
cfg.go_highlight_chan_whitespace_error = 1
cfg.go_highlight_extra_types = 1
cfg.go_highlight_space_tab_error = 1
cfg.go_highlight_trailing_whitespace_error = 1
cfg.go_highlight_operators = 1
cfg.go_highlight_functions = 1
cfg.go_highlight_function_parameters = 1
cfg.go_highlight_function_calls = 1
cfg.go_highlight_types = 1
cfg.go_highlight_fields = 1
cfg.go_highlight_build_constraints = 1
cfg.go_highlight_generate_tags = 1
cfg.go_highlight_string_spellcheck = 1
cfg.go_highlight_variable_declarations = 1
cfg.go_highlight_variable_assignments = 1


